language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
install:
  - conda build env_aurn_medmi.yml
  - conda install aurn_medmi --use-local
script:
  - python -m unittest discover